#pragma once
#define _CRT_SECURE_NO_WARNINGS
#include <vector>
#include <string>
#include <map>
#include <set>
#include <functional>
#include <memory>
#include <algorithm>
#include <fstream>
#include <sstream>
#include <cstdio>
